# -*- coding: utf-8 -*-
"""iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5pnBuyKUJpSXjNtosdFzVJSxSUrJHVb

# Processus d'un modèle de Machine Learning

Le développement d’un modèle de Machine Learning suit généralement les étapes suivantes :

### - Chargement des données
Importation des données à partir de fichiers, bases de données ou sources externes afin de constituer l’ensemble de travail.

### - Prétraitement des données
Nettoyage et transformation des données : suppression des valeurs manquantes, normalisation, encodage des variables et division en ensembles d’entraînement et de test.

### - Entraînement du modèle
Sélection d’un algorithme d’apprentissage (supervisé ou non supervisé) et ajustement de ses paramètres à partir des données d’entraînement.

### - Évaluation du modèle
Mesure des performances du modèle à l’aide de métriques telles que la précision, le rappel ou la F-mesure pour juger de sa fiabilité.

### - Prédiction
Utilisation du modèle entraîné pour effectuer des prédictions ou classifications sur de nouvelles données et interprétation des résultats.
"""

import pandas as pd # Manipulation de données
from sklearn.linear_model import LogisticRegression # logistic regression class
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from google.colab import files

# Charge le dataset et affiche les premières lignes
uploaded = files.upload()
iris_data = pd.read_csv("Iris.csv")
iris_data.head()

# Divise les données en features -> caractéristiques (X) et labels -> étiquettes (Y)
X = iris_data.drop(columns=['Id', 'Species'])
Y = iris_data['Species']

X.head()

# Divise les données en ensembles d'entraînement et de test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Standardise les features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Création d'un modèle de Machine Learning
model = LogisticRegression()

# Entrainement du modèle
model.fit(X_train_scaled, Y_train)

# Evaluation du modèle
Y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

# Échantillonner de nouvelles données pour la prédiction
new_data = np.array([[5.1, 3.5, 1.4, 0.2],
                     [6.3, 2.9, 5.6, 1.8],
                     [4.9, 3.0, 1.4, 0.2]])

# Standardise les nouvelles données
# Converti new_data en un DataFrame Pandas avec les mêmes noms de colonnes que X_train
new_data_df = pd.DataFrame(new_data, columns=X_train.columns)
new_data_scaled = scaler.transform(new_data_df)

# Processus de prédictions
predictions = model.predict(new_data_scaled)

# Affichage des prédictions
print("Predictions:", predictions)